name: deploy-main

on:
  push:
    branches:
      - main # main 브랜치에 새로운 커밋이 올라왔을 때 실행되도록 합니다.
    workflow_dispatch: # 필요한 경우 수동으로 실행할 수도 있도록 합니다.

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -TODO